<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ecl="urn:easee-gas.eu:edigas:codelistsV6" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- import the codelsits -->
	<xsd:import namespace="urn:easee-gas.eu:edigas:codelistsV6" schemaLocation="../cclib-v6/urn-easee-gas-eu-edigas-codelistsV6.xsd"/>
	<!-- include the local message restrictions -->
	<xsd:include schemaLocation="urn-easee-gas-eu-edigas-GasTradingOtc-RequestResponseDocument-6-1-local-restrictions.xsd"/>
	<!--  restricted codelists  -->
	<!-- CodingScheme type-->
	<xsd:simpleType name="StandardRestrictedCodingSchemeCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardCodingSchemeCodeTypeCodeList">
			<xsd:enumeration value="305"/>
			<xsd:enumeration value="ZSO"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CodingSchemeCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedCodingSchemeCodeTypeCodeList LocalRestrictedCodingSchemeCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Document type-->
	<xsd:simpleType name="StandardRestrictedDocumentCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardDocumentCodeTypeCodeList">
			<xsd:enumeration value="AMC"/>
			<xsd:enumeration value="AMD"/>
			<xsd:enumeration value="AMR"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocumentCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedDocumentCodeTypeCodeList LocalRestrictedDocumentCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- GasDirection type-->
	<xsd:simpleType name="StandardRestrictedGasDirectionCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardGasDirectionCodeTypeCodeList">
			<xsd:enumeration value="Z02"/>
			<xsd:enumeration value="Z03"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="GasDirectionCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedGasDirectionCodeTypeCodeList LocalRestrictedGasDirectionCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Role type-->
	<xsd:simpleType name="StandardRestrictedRoleCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardRoleCodeTypeCodeList">
			<xsd:enumeration value="ZSH"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RoleCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedRoleCodeTypeCodeList LocalRestrictedRoleCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- UnitOfMeasure type-->
	<xsd:simpleType name="ConversionUnitOfMeasureCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardUnitOfMeasureCodeTypeCodeList">
			<xsd:enumeration value="KW3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StandardRestrictedUnitOfMeasureCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardUnitOfMeasureCodeTypeCodeList">
			<xsd:enumeration value="KW1"/>
			<xsd:enumeration value="KW2"/>
			<xsd:enumeration value="TQH"/>
			<xsd:enumeration value="TQD"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="UnitOfMeasureCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedUnitOfMeasureCodeTypeCodeList LocalRestrictedUnitOfMeasureCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Quantity GasNature type-->
	<xsd:simpleType name="StandardRestrictedQuantityCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardQuantityCodeTypeCodeList">
			<xsd:enumeration value="Z36"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="QuantityCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedQuantityCodeTypeCodeList LocalRestrictedQuantityCodeTypeCodeList"/>
	</xsd:simpleType>	
</xsd:schema>