<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ecl="urn:easee-gas.eu:edigas:codelistsV6" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- import the codelsits -->
	<xsd:import namespace="urn:easee-gas.eu:edigas:codelistsV6" schemaLocation="../cclib-v6/urn-easee-gas-eu-edigas-codelistsV6.xsd"/>
	<!-- include the local message restrictions -->
	<xsd:include schemaLocation="urn-easee-gas-eu-edigas-CapacityAllocationReverseAuction-ReverseAuctionRequestDocument-6-1-local-restrictions.xsd"/>
	<!--  restricted codelists  -->
	<!-- Availabilitytype-->
	<xsd:simpleType name="StandardRestrictedAvailabilityCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardAvailabilityCodeTypeCodeList">
			<xsd:enumeration value="Z05"/>
			<xsd:enumeration value="Z06"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="AvailabilityCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedAvailabilityCodeTypeCodeList LocalRestrictedAvailabilityCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- CodingScheme type-->
	<xsd:simpleType name="StandardRestrictedCodingSchemeCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardCodingSchemeCodeTypeCodeList">
			<xsd:enumeration value="305"/>
			<xsd:enumeration value="ZSO"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CodingSchemeCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedCodingSchemeCodeTypeCodeList LocalRestrictedCodingSchemeCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- GasDirection type-->
	<xsd:simpleType name="StandardRestrictedGasDirectionCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardGasDirectionCodeTypeCodeList">
			<xsd:enumeration value="Z02"/>
			<xsd:enumeration value="Z03"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="GasDirectionCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedGasDirectionCodeTypeCodeList LocalRestrictedGasDirectionCodeTypeCodeList"/>
	</xsd:simpleType>	
	<!-- Currency type-->
	<xsd:simpleType name="StandardRestrictedCurrencyCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardCurrencyCodeTypeCodeList"/>
	</xsd:simpleType>
	<xsd:simpleType name="CurrencyCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedCurrencyCodeTypeCodeList LocalRestrictedCurrencyCodeTypeCodeList"/>
	</xsd:simpleType>	
	<!-- Document type-->
	<xsd:simpleType name="StandardRestrictedDocumentCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardDocumentCodeTypeCodeList">
			<xsd:enumeration value="AOE"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocumentCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedDocumentCodeTypeCodeList LocalRestrictedDocumentCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Reference type-->
	<xsd:simpleType name="StandardRestrictedReferenceCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardReferenceCodeTypeCodeList">
			<xsd:enumeration value="ZSF"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ReferenceCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedReferenceCodeTypeCodeList LocalRestrictedReferenceCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Role type-->
	<xsd:simpleType name="StandardRestrictedRoleCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardRoleCodeTypeCodeList">
			<xsd:enumeration value="ZUV"/>
			<xsd:enumeration value="ZUJ"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RoleCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedRoleCodeTypeCodeList LocalRestrictedRoleCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Transaction type-->
	<xsd:simpleType name="StandardRestrictedTransactionCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardTransactionCodeTypeCodeList">
			<xsd:enumeration value="ZSW"/>
			<xsd:enumeration value="ZSX"/>
			<xsd:enumeration value="ZSY"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TransactionCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedTransactionCodeTypeCodeList LocalRestrictedTransactionCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- UnitOfMeasure type-->
	<xsd:simpleType name="StandardRestrictedUnitOfMeasureCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardUnitOfMeasureCodeTypeCodeList">
			<xsd:enumeration value="KW1"/>
			<xsd:enumeration value="KW2"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="UnitOfMeasureCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedUnitOfMeasureCodeTypeCodeList LocalRestrictedUnitOfMeasureCodeTypeCodeList"/>
	</xsd:simpleType>
</xsd:schema>