<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ecl="urn:easee-gas.eu:edigas:codelistsV6" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- import the codelsits -->
	<xsd:import namespace="urn:easee-gas.eu:edigas:codelistsV6" schemaLocation="../cclib-v6/urn-easee-gas-eu-edigas-codelistsV6.xsd"/>
	<!-- include the local message restrictions -->
	<xsd:include schemaLocation="urn-easee-gas-eu-edigas-BrpNominationAndMatching-NominationAuthorisationDocument-6-1-local-restrictions.xsd"/>
	<!--  restricted codelists  -->
	<!-- CodingScheme type-->
	<xsd:simpleType name="StandardRestrictedCodingSchemeCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardCodingSchemeCodeTypeCodeList">
			<xsd:enumeration value="305"/>
			<xsd:enumeration value="ZSO"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CodingSchemeCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedCodingSchemeCodeTypeCodeList LocalRestrictedCodingSchemeCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- document type-->
	<xsd:simpleType name="StandardRestrictedDocumentCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardDocumentCodeTypeCodeList">
			<xsd:enumeration value="ANN"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocumentCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedDocumentCodeTypeCodeList LocalRestrictedDocumentCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Role type-->
	<xsd:simpleType name="StandardRestrictedRoleCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardRoleCodeTypeCodeList">
			<xsd:enumeration value="ZSH"/>
			<xsd:enumeration value="ZSO"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RoleCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedRoleCodeTypeCodeList LocalRestrictedRoleCodeTypeCodeList"/>
	</xsd:simpleType>
</xsd:schema>