<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ecl="urn:easee-gas.eu:edigas:codelistsV6" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- import the codelsits -->
	<xsd:import namespace="urn:easee-gas.eu:edigas:codelistsV6" schemaLocation="../cclib-v6/urn-easee-gas-eu-edigas-codelistsV6.xsd"/>
	<!-- include the local message restrictions -->
	<xsd:include schemaLocation="urn-easee-gas-eu-edigas-RemitAndTransparency-UmmDocument-6-1-local-restrictions.xsd"/>
	<!--  restricted codelists  -->
	<!-- CodingScheme type-->
	<xsd:simpleType name="StandardRestrictedCodingSchemeCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardCodingSchemeCodeTypeCodeList">
			<xsd:enumeration value="305"/>
			<xsd:enumeration value="ZSO"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CodingSchemeCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedCodingSchemeCodeTypeCodeList LocalRestrictedCodingSchemeCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Document type-->
	<xsd:simpleType name="StandardRestrictedDocumentCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardDocumentCodeTypeCodeList">
			<xsd:enumeration value="AOF"/>
			<xsd:enumeration value="ANX"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocumentCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedDocumentCodeTypeCodeList LocalRestrictedDocumentCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- GasDirection type-->
	<xsd:simpleType name="StandardRestrictedGasDirectionCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardGasDirectionCodeTypeCodeList">
			<xsd:enumeration value="Z02"/>
			<xsd:enumeration value="Z03"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="GasDirectionCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedGasDirectionCodeTypeCodeList LocalRestrictedGasDirectionCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- Status type-->
	<xsd:simpleType name="StandardRestrictedStatusCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardStatusCodeTypeCodeList">
			<xsd:enumeration value="62G"/>
			<xsd:enumeration value="69G"/>
			<xsd:enumeration value="70G"/>			
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StatusCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedStatusCodeTypeCodeList LocalRestrictedStatusCodeTypeCodeList"/>
	</xsd:simpleType>	
	<!-- ResourceCode type-->
	<xsd:simpleType name="StandardRestrictedResourceTypeCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardResourceTypeCodeTypeCodeList">
			<xsd:enumeration value="A01"/>
			<xsd:enumeration value="A02"/>
			<xsd:enumeration value="A03"/>
			<xsd:enumeration value="A04"/>
			<xsd:enumeration value="A05"/>
			<xsd:enumeration value="A06"/>
			<xsd:enumeration value="A07"/>
			<xsd:enumeration value="A08"/>
			<xsd:enumeration value="A09"/>
			<xsd:enumeration value="A10"/>
			<xsd:enumeration value="A11"/>
			<xsd:enumeration value="A12"/>			
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ResourceTypeCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedResourceTypeCodeTypeCodeList LocalRestrictedResourceTypeCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- ReasonCode type-->
	<xsd:simpleType name="StandardRestrictedReasonCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardReasonCodeTypeCodeList">
			<xsd:enumeration value="22G"/>
			<xsd:enumeration value="25G"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ReasonCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedReasonCodeTypeCodeList LocalRestrictedReasonCodeTypeCodeList"/>
	</xsd:simpleType>			
	<!-- Role type-->
	<xsd:simpleType name="StandardRestrictedRoleCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardRoleCodeTypeCodeList">
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RoleCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedRoleCodeTypeCodeList LocalRestrictedRoleCodeTypeCodeList"/>
	</xsd:simpleType>
	<!-- UnitOfMeasure type-->
	<xsd:simpleType name="StandardRestrictedUnitOfMeasureCodeTypeCodeList">
		<xsd:restriction base="ecl:StandardUnitOfMeasureCodeTypeCodeList">
			<xsd:enumeration value="KW1"/>
			<xsd:enumeration value="KW2"/>
			<xsd:enumeration value="HM2"/>						
			<xsd:enumeration value="GWH"/>
			<xsd:enumeration value="GM1"/>			
			<xsd:enumeration value="GM2"/>						
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="UnitOfMeasureCodeTypeCodeList">
		<xsd:union memberTypes="StandardRestrictedUnitOfMeasureCodeTypeCodeList LocalRestrictedUnitOfMeasureCodeTypeCodeList"/>
	</xsd:simpleType>
</xsd:schema>
